title: Minsu Kim
author: Business&Data Analyst, Growth Hacker
email: justdoms96@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  데이터에서 비지니스 문제의 인사이트를 찾고, 해결하고, 생각하는
  경영학도입니다. 실패에서 오는 경험을 즐기려고 노력하고 있습니다.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Minsu Kim
  tagline: |
    Business&Data Analyst, Growth Hacker

    데이터에서 비지니스 문제의 인사이트를 찾고, 해결하고, 생각하는 경영학도입니다.

    #python #MySQL #GA #BI #machinelearning
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp

  # generate social links in footer
  social_links:
    github:  MINSUKIM-BA/portfolio
    linkedIn: in/thelehhman
    instagram: minshu_96
  navigation:
    - title: POST
      url: "/posts"
    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
